### ISSUE TITLE
Using bundler >=2 breaks CI

### ISSUE THREAD

**Issue by llekn** [platanus/potassium#204]
Newly created projects use bundler 2.0.1 in their `Gemfile` which breaks the CI with the following error:

```
You must use Bundler 2 or greater with this lockfile
```

**Comment by llekn** [comment]
It can be fixed modifying the `docker-ci` files:

`Dockerfile.ci`:

```dockerfile
FROM platanus/ruby:2.5

RUN gem install bundler --version 2.0.1

RUN mkdir /app
WORKDIR /app

ADD . /app
```

`docker-compose.ci.yml`:

```YAML
---
version: '3.4'
services:
  test:
    build:
      context: "."
      dockerfile: Dockerfile.ci
    volumes:
    - "test_data:/usr/local/bundle"
    environment:
      RACK_ENV: test
      DB_USER: postgres
      DB_HOST: postgresql
      DB_PORT: '5432'
    links:
    - postgresql
  postgresql:
    image: postgres:11.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
volumes:
  test_data:
```
