### ISSUE TITLE
RSpec/EmptyExampleGroup with Swagger

### ISSUE THREAD

**Issue by GabrielLyonB** [platanus/potassium#362]
Swagger Api tests/documentation needs to include `run_test!` as a valid example group for Rubocop rules. 
``` yml
RSpec:
  Language:
    Includes:
      Examples:
        - run_test!
```
Link to more information [here](https://docs.rubocop.org/rubocop-rspec/upgrade_to_version_2.html#configuration-file-update).
